[project]
name = "wild-woods-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "esper>=3.7",
    "noise>=1.2.2",
    "pygame-ce>=2.5.6",
]

[dependency-groups]
dev = [
    "basedpyright>=1.38.2",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.2",
    "taskipy>=1.14.1",
]

[tool.uv]
package = true

[project.scripts]
game = "client.main:main"

[tool.taskipy.tasks]
lint = "ruff check src --fix"
format = "ruff format src"
check = "mypy src && basedpyright"
test = "pytest"
all = "task format && task lint && task check"
init = "git config core.hooksPath .githooks"


[tool.ruff.lint]
ignore = ["F841"]


[tool.mypy]
mypy_path = "src"
explicit_package_bases = true

[[tool.mypy.overrides]]
module = "noise"
ignore_missing_imports = true

[tool.basedpyright]
stubPath = "typings"
reportUnusedCallResult = "none"
reportMissingTypeStubs = "none"
exclude = [
    "tests",
    "**/__pycache__",
    ".venv"
]
